#! /bin/bash

#################################################
#   	 	MongoDB Installer		#
#################################################

# DEBUG #
# set -x

# RUN AS ROOT # (sudo/doas)
if [[ `id -u` -ne 0 ]]; then
	printf "Please run as root.\n"
	exit
fi

# VARS #
version=

Header(){
	printf "########################################################################\n"
	printf "#--------------------> MongoDB Installer v0.1.01a <--------------------#\n"
	printf "########################################################################\n"

}

# UPDATE pacman #
source update

# INSTALL OFFICIAL PACKAGES #
Header
if ! command -v paru &> /dev/null; then
	printf "yay cannot be found. Please install yay and try again."
	exit
fi

printf "Beginning installation of packages.\n"
paru -S mongodb mongodb-tools
