#! /bin/bash

# DEBUG #
# set -x

# RUN AS ROOT # (sudo/doas)
if [[ `id -u` -ne 0 ]]; then
	printf "Please run as root.\n"
	exit
fi

# VARS #
version=v0.1.01a
cloneDir=/usr/.clones

Help(){
	printf "########################################################################\n"
	printf "#-----------------> Fresh Package Installer %s <-----------------#\n"	$version
	printf "#--------------------> Were Verobsity Is Default. <--------------------#\n"
	printf "#----------------> Author: https://github.com/wjorden <----------------#\n"
	printf "########################################################################\n"
	printf "#-> Syntax: dev_installer [-d|h]\n"
	printf "#-> Options:\n"
	printf "##-> -d PATH	Specify path for git clones. Default is /usr/.clones/\n"
	printf "##-> -	\n"
	printf "##-> -h		Print this help.\n"
}

# Handle options
while getopts d:ht flag
do 
	case "${flag}" in
		d) 
			cloneDir=${OPTARG};;
		h | t) 
			Help 
			exit;;
	esac
done

